services:
  web:
    restart: always
    build: .
    links:
      - postgres:postgres

    environment:
      DEBUG: False
      POSTGRES_HOST: "postgres"
      POSTGRES_DB: "Task_Manager_DB"  #Название базы данных postgres
      DATABASE_PORT: "5432"
      POSTGRES_USER: "postgres"  #Название пользователя базы данных
      POSTGRES_PASSWORD: "rtf558Ur" #Пароль пользователя базы данных
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: >
      sh -c "PYTHONPATH=. python app/tm_app.py"

  postgres:
    hostname: postgres
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: "Task_Manager_DB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "rtf558Ur"
    ports:
      - "5432:5432"

volumes:
  db-data: